### ISSUE TITLE
Joystick Teleop Migration

### ISSUE THREAD

**Issue by maxsvetlik** [utexas-bwi/bwi_experimental#24]
The joystick teleop package has dependencies that don't get caught with the initial run of rosdep (since its in bwi_experimental). This means that none of our code base can depend on this package.

It'd be better suited for bwi_common or segbot

**Comment by FernandezR** [comment]
Moved it over to segbot and submitted a pull request.

**Comment by jack-oquin** [comment]
It's merged into bwi_common now.
