### ISSUE TITLE
bwi_virtour: cannot launch node of type [mjpeg_server/mjpeg_server]: mjpeg_server

### ISSUE THREAD

**Issue by shiqizhang6** [utexas-bwi/bwi_experimental#30]
@pato

**Comment by pato** [comment]
mjpeg_serve was deprecated and replaced by web_video_server so I will take this opportunity to upgrade all usage to use the new version, that is probably why it wasn't working

**Comment by shiqizhang6** [comment]
@pato Do you think the recent commit can fix this issue? If so, we can close it.

**Comment by pato** [comment]
@shiqizhang6 Yep! This is now fixed
