### ISSUE TITLE
[bwi_virtour/servceCertificates.sh]: can't locate node [servceCertificates.sh] in package [bwi_virtour]

### ISSUE THREAD

**Issue by shiqizhang6** [utexas-bwi/bwi_experimental#32]
@pato 

This error keeps showing up when I ran virtour_full.launch

ERROR: cannot launch node of type [bwi_virtour/servceCertificates.sh]: can't locate node [servceCertificates.sh] in package [bwi_virtour]

**Comment by pato** [comment]
Hey!

I think its because i had a typo! it should be
`bwi_virtour/serveCertificates.sh`
